version: '3'

services:
  game-server:
    image: llmctf/2025q-pwn-mooneys_bookstore
    privileged: true
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io
    ports:
      - 21006:21006

networks:
  ctfnet:
    external: true